[[listen]]
protocol = "trojans"
uuid = "a684455c-b14f-11ea-bf0d-42010aaa0003"
network = "unix"
host = "/dev/shm/ws.sock"
insecure = true
fallback = ":80"
cert = "cert.pem"
key = "cert.key"
advancedLayer = "ws"
path = "/ohmygod_verysimple_is_very_simple"
early = true 

[[dial]]
protocol = "direct"
# fullcone = true
