[[listen]]
protocol = "socks5"
host = "127.0.0.1"
port = 10800


[[dial]]
protocol = "vmess"
uuid = "a684455c-b14f-11ea-bf0d-42010aaa0003"
host = "127.0.0.1"
port = 4434

extra = { vmess_security = "aes-128-gcm" }  # 其他可能的值: "chacha20-poly1305", "auto", "none", ""

encrypt_algo = "aes-128-gcm"    #最新vs代码 添加了新的 encrypt_algo配置项, 同样可以配置 vmess 的 security; 它和 extra.vmess_security 同时出现时，encrypt_algo 会覆盖 extra.vmess_security

# 这里vs为了保护用户，如果不给出内部加密方式，会自动设为auto，而不是zero

# 具体none和zero的区别, 以及 auto 的含义, 详见 https://www.v2fly.org/config/protocols/vmess.html#userobject
