name: Build For Release Extra

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: 'tagName'     
        required: true

jobs:
  vsc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        goarch: [amd64, arm64]


    env:
      THEOS: ${{ matrix.os }}
      GOARCH: ${{ matrix.goarch }}
      CGO_ENABLED: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tagName }}

      - name: Show workflow information 
        id: get_filename
        run: |
          export _NAME=vs_gui_${{ matrix.os }}_${{ matrix.goarch }}
          echo "THEOS: $THEOS, GOARCH: $GOARCH, RELEASE_NAME: $_NAME"
          echo "::set-output name=ASSET_NAME::$_NAME"
          echo "ASSET_NAME=$_NAME" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Build
        run: |
          cd cmd/verysimple/ && make -f Makefile_r_vsc PACKNAME=vs_gui_${{ steps.get_filename.outputs.ASSET_NAME }} BUILD_VERSION=${{ github.event.inputs.tagName }}
      
      - name: touch xz archive
        shell: bash
        run: |
          cd cmd/verysimple/ && touch -mt $(date +%Y01010000) *.tar.xz
      
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: cmd/verysimple/*.tar.xz
          tag: ${{ github.event.inputs.tagName }}
          file_glob: true

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.tagName }}

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    
    - name: Build
      run: |
        cd cmd/verysimple/ && make -f Makefile_release extra PACK=1 BUILD_VERSION=${{ github.event.inputs.tagName }}
    
    - name: touch xz archive
      shell: bash
      run: |
        cd cmd/verysimple/ && touch -mt $(date +%Y01010000) *.tar.xz
    
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: cmd/verysimple/*.tar.xz
        tag: ${{ github.event.inputs.tagName }}
        file_glob: true
