name: Build For Release Extra

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: 'tagName'     
        required: true

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.tagName }}

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    
    - name: Build
      run: |
        cd cmd/verysimple/ && make -f Makefile_release extra PACK=1 BUILD_VERSION=${{ github.event.inputs.tagName }}
    
    - name: touch xz archive
      shell: bash
      run: |
        cd cmd/verysimple/ && touch -mt $(date +%Y01010000) *.tar.xz
    
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: cmd/verysimple/*.tar.xz
        tag: ${{ github.event.inputs.tagName }}
        file_glob: true
