name: Build For Release Extra

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: 'tagName'     
        required: true

jobs:
  vsc_ubuntu_arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tagName }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Run commands
        run: |
          apt-get update -q -y
          apt-get install -q -y build-essential libgtk-3-dev wget gcc-aarch64-linux-gnu
          echo "CC=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
          CC="aarch64-linux-gnu-gcc"
          cd cmd/verysimple/ && make -f Makefile_r_vsc PACKNAME=vs_gui_ubuntu_arm64 BUILD_VERSION=${{ github.event.inputs.tagName }} && touch -mt $(date +%Y01010000) *.tar.xz

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: cmd/verysimple/*.tar.xz
          tag: ${{ github.event.inputs.tagName }}
          file_glob: true

  vsc:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        goarch: [amd64]
        include:
          - os: macos-latest
            goarch: arm64
      fail-fast: false

    runs-on: ${{ matrix.os }}

    env:
      THEOS: ${{ matrix.os }}
      GOARCH: ${{ matrix.goarch }}
      CGO_ENABLED: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tagName }}

      - if: ${{ matrix.os  == 'ubuntu-latest' }}
        name: install dependency for ubuntu
        run: |
          sudo apt-get install build-essential libgtk-3-dev

      - if: ${{ matrix.os  != 'windows-latest' }}
        name: set ASSET_NAME
        run: |
          echo "ASSET_NAME=vs_gui_${{ matrix.os }}_${{ matrix.goarch }}" >> $GITHUB_ENV

      - if: ${{ matrix.os  == 'windows-latest' }}
        name: set ASSET_NAME
        run: |
          echo "ASSET_NAME=vs_gui_${{ matrix.os }}_${{ matrix.goarch }}" | Out-File -FilePath $env:GITHUB_ENV -Append 

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Build
        run: |
          cd cmd/verysimple/ && make -f Makefile_r_vsc PACKNAME=${{ env.ASSET_NAME }} BUILD_VERSION=${{ github.event.inputs.tagName }}
      
      - name: touch xz archive
        shell: bash
        run: |
          cd cmd/verysimple/ && touch -mt $(date +%Y01010000) *.tar.xz
      
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: cmd/verysimple/*.tar.xz
          tag: ${{ github.event.inputs.tagName }}
          file_glob: true

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.tagName }}

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    
    - name: Build
      run: |
        cd cmd/verysimple/ && make -f Makefile_release extra PACK=1 BUILD_VERSION=${{ github.event.inputs.tagName }}
    
    - name: touch xz archive
      shell: bash
      run: |
        cd cmd/verysimple/ && touch -mt $(date +%Y01010000) *.tar.xz
    
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: cmd/verysimple/*.tar.xz
        tag: ${{ github.event.inputs.tagName }}
        file_glob: true
