name: Build For Release Extra

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: 'tagName'     
        required: true

jobs:
  xgo:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build vsc(verysimple client)
        uses: crazy-max/ghaction-xgo@v2
        with:
          xgo_version: latest
          go_version: 1.19
          dest: build
          prefix: vsc
          targets: windows/amd64,windows/arm64,linux/amd64,linux/arm64,darwin/amd64,darwin/arm64
          v: true
          x: false
          race: false
          ldflags: -s -w -ldflags "-X 'main.Version=${{ github.event.inputs.tagName }}' -buildid="
          buildmode: default
          trimpath: true
          working_dir: cmd/verysimple
          tags: "vcs"

      - name: create xz archive
        shell: bash
        run: |
          cd cmd/verysimple/ && for i in vsc*; do tar -cJf $i.tar.xz $i -C ../../ examples/; done && touch -mt $(date +%Y01010000) *.tar.xz

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: cmd/verysimple/vsc*.tar.xz
          tag: ${{ github.event.inputs.tagName }}
          file_glob: true

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.tagName }}

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    
    - name: Build
      run: |
        cd cmd/verysimple/ && make -f Makefile_release extra PACK=1 BUILD_VERSION=${{ github.event.inputs.tagName }}
    
    - name: touch xz archive
      shell: bash
      run: |
        cd cmd/verysimple/ && touch -mt $(date +%Y01010000) *.tar.xz
    
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: cmd/verysimple/*.tar.xz
        tag: ${{ github.event.inputs.tagName }}
        file_glob: true
